"""eliminar trimestre

Revision ID: 2271dd0bbffa
Revises: d2a28c7a6938
Create Date: 2026-06-27 12:05:16.287753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2271dd0bbffa'
down_revision = 'd2a28c7a6938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_column('trimestre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trimestre', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
